import Provider from '@/components/Provider';
import './globals.css'
import Navbar from '@/components/ui/Navbar'
import { Poppins } from 'next/font/google';
const poppins = Poppins({ weight: ['400', '600', '700', '900'], subsets: ['latin'], variable: '--font-poppins' })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className} `}>
        <Provider>
          <Navbar />
          {children}
        </Provider>


      </body>
    </html>
  )
}
